[tools]
swiftgen = "6.6.3"
swiftlint = "0.65.1"
tuist = "4.207.0"

[tasks.swiftgen]
run = "swiftgen"

[tasks.swiftlint]
run = "swiftlint"

[tasks.install]
run = "mise exec -- tuist install"

[tasks.generate]
run = "mise exec -- tuist generate --no-open"

[tasks.test]
run = "xcodebuild -workspace SwiftExplorer.xcworkspace -scheme SwiftExplorer -destination 'platform=macOS,arch=x86_64' -skipPackagePluginValidation clean test"
