name: CI
on: [pull_request]

jobs:
  build:
    runs-on: macOS-26

    steps:
      - uses: actions/checkout@v6

      - name: Read Xcode version
        id: xcode_version
        run: echo "XCODE_VERSION=$(cat .xcode-version)" >> $GITHUB_ENV

      - name: Setup Xcode using .xcode-version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Run tests
        run: |
          xcodebuild \
            -project SwiftExplorer.xcodeproj \
            -scheme "SwiftExplorer" \
            -destination "platform=macOS,arch=x86_64" \
            -skipPackagePluginValidation \
            clean test || true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          swift: true
          swift_project: SwiftExplorer
          verbose: true
